apache/brooklyn-ui

LICENSE, src/build/optimize-js.json, src/main/license/files/LICENSE, src/main/license/source-inclusions.yaml, src/main/webapp/assets/css/brooklyn.css, src/main/webapp/assets/css/codemirror.css, src/main/webapp/assets/css/show-hint.css, src/main/webapp/assets/js/addon/display/placeholder.js, src/main/webapp/assets/js/addon/hint/anyword-hint.js, src/main/webapp/assets/js/addon/hint/show-hint.js, src/main/webapp/assets/js/config.js, src/main/webapp/assets/js/lib/codemirror.js, src/main/webapp/assets/js/libs/bootstrap.js, src/main/webapp/assets/js/libs/js-yaml.js, src/main/webapp/assets/js/mode/yaml/yaml.js, src/main/webapp/assets/js/model/catalog-application.js, src/main/webapp/assets/js/router.js, src/main/webapp/assets/js/util/brooklyn-utils.js, src/main/webapp/assets/js/view/application-add-wizard.js, src/main/webapp/assets/js/view/catalog.js, src/main/webapp/assets/js/view/editor.js, src/main/webapp/assets/tpl/app-add-wizard/create.html, src/main/webapp/assets/tpl/editor/page.html, src/main/webapp/index.html, src/test/javascript/config.txt, src/test/javascript/specs/view/application-add-wizard-spec.js
Continuatiion of work started in https://github.com/apache/incubator-brooklyn/pull/865 by @azbarcea for [BROOKLYN-166](https://issues.apache.org/jira/browse/BROOKLYN-166)
=> [BROOKLYN-166] Replace existing textareas for editing  YAML with Composer Tab + Codemirror

pom.xml, src/main/webapp/assets/img/zeroclipboard/.gitignore, src/main/webapp/assets/img/zeroclipboard/README.md, src/main/webapp/assets/js/libs/ZeroClipboard.js, src/main/webapp/assets/js/view/entity-config.js, src/main/webapp/assets/js/view/entity-sensors.js
fixes issues in some recent browser (eg latest chrome on latest os x)
where the flash "movie" won't load unless it is local.
the error it gives is a generic "uncaught exception" in
ZeroClipboard activate -> flashState.bridge.setSize.
curiously it still works fine in some browsers (firefox) and
older chrome was also fine but I'm guessing
security modes are being tightened in browsers.
none of the other recommended settings for fixing this seem to work:
* trustedDomains
* trustedOrigin
* allowScriptAccess
* and even the flash config in the browser
it's just a small movie however so should be low impact (smaller than most of our images).
put in img path to simplify access.
also, zeroclipboard is updated from 1.3.1 to 1.3.5 (latest stable 1.x branch).
(2.x branch looks like it might be a …
=> use local version of zeroclipboard movie

src/main/webapp/assets/js/config.js
This PR follows the proposal on the mailing list about allowing the REST API to be relocated relative to brooklyn's web UI.
For now the function is not changed, but this allows administrators to deploy Brooklyn's REST API and its UI indepentent of each other's base URLs.
=> Allow relocation of Brooklyn REST API

src/main/webapp/assets/js/view/catalog.js, src/main/webapp/assets/tpl/catalog/details-location.html
takes advantage of improvements in https://github.com/apache/brooklyn-server/pull/70 esp in rest api to make the locations shown in catalog more informative and useful, disabling delete for those which can't be deleted, and even allowing editing for those following the new style of adding to the catalog
(should work nicely in conjunction with #17 !)
note this requires https://github.com/apache/brooklyn-server/pull/70
=> Improve catalog locations info and editability

src/main/webapp/assets/js/config.js, src/main/webapp/assets/js/router.js
This is mainly to prevent javascript errors with jQuery not available when running Brooklyn from `BrooklynJavascriptGuiLauncher`
=> Move jQuery code inside a closure managed by require

src/main/webapp/assets/css/codemirror-brooklyn.css, src/main/webapp/assets/js/view/editor.js, src/main/webapp/assets/tpl/editor/page.html
This loads straight away CodeMirror when launching the composer from the composer tab, removing the requirement on loading the full list of applications contained within the catalog.
When coming from the catalog (editing a catalog item YAML), it will temporarily disable the editor, add an overlay displaying `Loading item...` until the item is full loaded from the REST server and added to the editor. At that point, the overlay will fade out and the editor enable again.
=> BROOKLYN-244: Fix blueprint composer loading issue

src/main/webapp/assets/js/view/editor.js, src/main/webapp/assets/tpl/editor/page.html
The text now makes it clear that users can use drag & drop to add text files' content into the editor
=> Update editor placeholder

src/main/webapp/assets/js/view/location-wizard.js
This avoids breaking other parts of the UI
=> Hotfix: Skip the creation of the contains method within Array prototype

src/main/webapp/assets/js/view/location-wizard.js
The wizard previously used `jclouds:openstack` and adding to the catalogue threw an error with "Transformer for Brooklyn OASIS CAMP interpreter gave an error creating this plan: No class or resolver found for location type jclouds:openstack"
=> Location wizard generates correct spec for Openstack

src/main/webapp/assets/js/view/application-add-wizard.js
I hope the title explains what it is fixing
I see that the `StepDeploy.validate` does more than validating the model.
Any suggestions for separating this logic or renaming the validate method to `fillConfigAndValidate`?
I do not understand how `ModalWizard`, `ModalWizard.StepCreate` and `ModalWizard.StepDeploy` are connected to each other.
@tbouron any comments?
=> Show config values when jumping from App Wizard to YAML Preview

src/main/webapp/assets/js/view/location-wizard.js
This update the field `privateKeyFile` to `privateKeyData`.
It also checks if a configuration key contains line breaks. In that case, it will generate a valid multiline YAML.
=> BROOKLYN-275: Location wizard generates valid YAML for multiline fields

src/main/webapp/assets/js/model/server-extended-status.js, src/main/webapp/assets/js/router.js
Minor tweaks to opt-in to CSRF protection in Brooklyn UI
NB requires https://github.com/apache/brooklyn-server/pull/430
(actually it will work fine without that, but it will be no-op)
=> request and set the csrf header protection added to brooklyn server

.mvn/jvm.config, pom.xml, src/main/webapp/logout_redirect.html
* Will be picked up when building a sub-module
* Doesn't work with `--file` option ([MNG-5889](https://issues.apache.org/jira/browse/MNG-5889))
=> Set default JVM memory settings for the build

src/main/webapp/assets/html/swagger-ui.html
Since Brooklyn checks for CSRF header for every POST/PUT requests, the relevant methods didn't work anymore on the swagger UI page.
This fixes it by setting the header manually into the swagger configuration
=> [BROOKLYN-408] Add CSRF header on the swagger page

src/main/webapp/assets/js/view/editor.js
As for today, when a user submit catalog item(s), the UI redirects to the catalog page, not to the newly created catalog item. This is due to the fact that the UI does not know what type of catalog item has been created and therefore cannot redirect the user properly.
This corrects this behaviours.
_Note: This requires https://github.com/apache/brooklyn-server/pull/567 **to be merged first**_
=> Use the "itemType" to redirect the user to the right page after a catalog import

src/main/webapp/assets/html/swagger-ui.html, src/main/webapp/assets/js/logout.js, src/main/webapp/assets/js/util/brooklyn-utils.js, src/main/webapp/logout.html
- BROOKLYN-323: Simplify LogoutApi
- relative urls for swagger html
PR depends on https://github.com/apache/brooklyn-server/pull/578
Previously when you are on the API page dropdown menu was not visible.
=> Updated logout step to work in karaf mode

src/main/webapp/assets/js/view/catalog.js, src/main/webapp/assets/js/view/editor.js
**Requires https://github.com/apache/brooklyn-server/pull/638**
This adds a new accordion to display enrichers registered within the Brooklyn catalog
=> Add support for enricher catalog items

src/main/webapp/assets/js/model/server-extended-status.js
fix it by accepting null plane as acceptable if server is otherwise healthy
=> if not using persistence and mgmt plane ID is null, UI can give erroneous error

pom.xml
This is to fix the build (which uses Docker) on apache Jenkins: https://builds.apache.org/job/brooklyn-ui-master-docker/
It follows the same convention as this commit: https://github.com/apache/brooklyn-server/commit/b18d9699884faa3285f1fd256da1dc429f9096e0
This is necessary because `brooklyn-ui` parent pom is no `brooklyn-parent`
=> Add local .m2 cache to list of exclusion for RAT plugin

pom.xml
As `brooklyn-ui` doesn't use `brooklyn-parent`, we need to add the local maven cache for the Jenkins build
=> Add .m2 folder in the list of ignore folders for the RAT plugin

README.md, docs/customizations.md, docs/vanilla-with-custom-widget.bom, ui-modules/blueprint-composer/app/components/custom-config-widget/suggestion-dropdown.html, ui-modules/blueprint-composer/app/components/custom-config-widget/suggestion-dropdown.js, ui-modules/blueprint-composer/app/components/custom-config-widget/suggestion-dropdown.less, ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/index.js, ui-modules/blueprint-composer/app/index.less
Adds the ability to define custom widgets for config, and supplies one such with an example as shown in `docs/vanilla-with-custom-widget.bom`.
=> Customizable config widgets

modularity-server/README.md, modularity-server/external-modules/src/main/java/org/apache/brooklyn/ui/modularity/ExternalUiModule.java, modularity-server/external-modules/src/main/java/org/apache/brooklyn/ui/modularity/enricher/BrooklynExternalUiModuleEnricher.java, modularity-server/module-api/pom.xml, modularity-server/module-api/src/main/java/org/apache/brooklyn/ui/modularity/module/api/UiModule.java, modularity-server/module-api/src/main/java/org/apache/brooklyn/ui/modularity/module/api/UiModuleListener.java, modularity-server/module-api/src/main/java/org/apache/brooklyn/ui/modularity/module/api/internal/UiModuleImpl.java, ui-modules/home/app/views/main/main.controller.js, ui-modules/home/src/main/resources/ui-module/config.yaml, ui-modules/home/src/main/webapp/WEB-INF/web.xml, ui-modules/utils/module-links/module-links-drawer.template.html, ui-modules/utils/module-links/module-links-navbar.template.html, ui-modules/utils/module-links/module-links.js
Either by stopping other bundles listening on the same context-path or by specifying bundles superseded by a module being installed.  See `README.md` for more info.
=> Allow UI modules to actively resolve conflicts

ui-modules/blueprint-composer/app/components/dsl-viewer/dsl-viewer.js, ui-modules/blueprint-composer/app/views/main/graphical/edit/dsl/edit.dsl.controller.js
This fixes 2 bugs:
1. When adding a DSL for an entity spec, The DSL editor "Done" button was not redirecting to the spec editor. This was due to the previous param object being modified later on by the `ui-router`. Creating a deep copy of the object avoid this
2. The DSL viewer was throwing an error while getting the name of the entity for DSL like `$brooklyn:self()` or `$brooklyn:parent()`. This is fixed by looking up directly for the relationships if the DSL are of that form
=> Fix bug with the DSL editor/viewer

ui-modules/blueprint-composer/app/components/designer/designer.directive.js, ui-modules/blueprint-composer/app/components/util/d3-blueprint.js
As a blueprint author
I want to be able to delete entities present on the graphic view of the Blueprint Composer by hitting the backspace/delete key on my keyboard
So that I can write blueprints faster (especially as a user who prefers keyboards to mice).
=> Blueprint composer deletes entities with backspace/delete key

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js, ui-modules/blueprint-composer/app/views/main/yaml/yaml.state.js
makes it easier for other entities to work with memberSpecs, in composer or yaml editor
=> recognize memberSpec anywhere, and refresh blueprint within yaml editor

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
Adds UI support for constraints introduced in https://github.com/apache/brooklyn-server/pull/999
=> More constraints

ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js
The palette should also search the entity's tags, when filtering. People can use tags to categorise or provide additional metadata, so this is useful to include.
=> Composer palette: search entity tags

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/utils/autogrow/index.js, ui-modules/utils/on-enter/index.js
Fix firefox multi-lines issue in configuration text-area in the blueprint composer
- replace white-space "nowrap" by "pre" otherwise firefox doesn't display new lines
- handle shift+enter (in addition to ctrl+enter and option+enter) to create a new line
- avoid javascript error when the input is empty and new line is inserted
Signed-off-by: Ludovic Plantin <ludovic.plantin@usharesoft.com>
=> Fix firefox multi-lines issue in configuration text-area

ui-modules/blueprint-composer/app/components/providers/palette-api.js, ui-modules/blueprint-composer/app/components/providers/palette-api.provider.js
The palette API was missing crucial endpoints used to load blueprint from the catalog UI module.
This also fixes a typo in for the `getTypeVersions` method name => `s/getTypeVersion/getTypeVersions`
=> Implement missing endpoint for palette API

modularity-server/external-modules/pom.xml, modularity-server/features/pom.xml, modularity-server/metadata-registry/pom.xml, modularity-server/module-api/pom.xml, modularity-server/proxy/pom.xml, pom.xml
Works with apache/brooklyn-server#1002
Removes the use of a `Service-Component` which is no longer supported by `karaf`.
Specifies the pax-web component versions as a property.
=> Support for karaf 4.2.1 and running under JDK 11

ui-modules/blueprint-composer/app/components/util/d3-blueprint.js
Previously, there was an issue on the memberspec node's animation when a cluster had more than one child. This fixes it for both Chrome and Firefox
=> Fix image animation for memberspec when there are children to the cluster

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
Previously, the `Remove` item present within the overflow menu (top right) of the `spec-editor` wasn't removing an adjunct. There was 2 issues causing this behaviour:
1. The `Remove` item wasn't checking the entity family, hence didn't delete any adjunct (as methods are different than removing a child)
2. The `refreshTypeMetadata` was setting the wrong entity family for adjuncts
=> Fix the remove button within overflow menu for adjuncts

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.template.html, ui-modules/blueprint-composer/app/components/designer/designer.less, ui-modules/blueprint-composer/app/components/providers/palette-service.provider.js, ui-modules/blueprint-composer/app/index.js, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.html, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.less, ui-modules/blueprint-composer/app/views/main/main.less, ui-modules/blueprint-composer/app/views/main/main.template.html, ui-modules/utils/br-core/style/buttons.less
This allows to:
- add multiple visualisations, if we wish to. Will be added as tabs
- customise palettes. Add/remove sections, they are on the left side
- separate the palette from the configuration screen, less confusing for users
- hide both the palette and spec editor for showing off the blueprint fullscreen
Here is how it looks (Sorry, GitHub does not support video upload in comments)
https://drive.google.com/file/d/1-6b-q6K4mxy3-HSSmRqDLamkVgTliCdZ/view?usp=sharing
=> New layout for the blueprint composer

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/providers/palette-api.js, ui-modules/blueprint-composer/app/components/providers/palette-api.provider.js
One possible use case of the composer is to have a custom palette that represents several elements ("virutal types") that are based on the same brooklyn type with different brooklyn configuration (referencing different external element like docker image or, in our case, UForge appliance).
In that use case, with the following yaml
```
services:
- type: com.usharesoft.brooklyn.type.LinuxAppliance
brooklyn.config:
applianceUUID: 'AAAA-AAAA-AAAA'
- type: com.usharesoft.brooklyn.type.LinuxAppliance
brooklyn.config:
applianceUUID: 'BBBB-BBBB-BBBB'
- type: com.usharesoft.brooklyn.type.LinuxAppliance
brooklyn.config:
applianceUUID: 'AAAA-AAAA-AAAA'
```
the three services of the same `com.usharesoft.brooklyn.type.LinuxAppliance` brooklyn type should be resolved by two different "virtual" types …
=> Allow to resolve different virtual type according to the entity config

ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.js
This change means that the DSL editor will let you choose a reference to an entity in any config key (rather than only if the config key is of type `Entity`).
This makes it more consistent with the rest of the DSL editor: e.g. if generating `attributeWhenReady`, it doesn't type-check the attributes' types to filter the view to only those that match the config key's type. This is a good thing, because otherwise we'd have to repeat all the type coercion rules in the UI, for it to know what is legal!
---
I tested this by running `npm run start` in brooklyn-ui/ui-modules/blueprint-composer. I chose a couple of arbitrary entities, and successfully wired up a config key's value to reference the other entity:
=> DSL editor: allow ref to entity anywhere

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/util/d3-blueprint.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js
As the title say, this expand the relationship support to memberspecs, i.e. if a memberspec has a DSL pointing to any other entity, it will now display an arrow to it.
Here is how it looks like:
And this done with the classic 3 tier webapp blueprint:
```yaml
name: My Web Cluster
services:
- type: org.apache.brooklyn.entity.database.mysql.MySqlNode
id: db
name: My DB (MySQL)
brooklyn.config:
datastore.creation.script.url: >-
https://raw.githubusercontent.com/apache/brooklyn-library/master/examples/simple-web-cluster/src/main/resources/visitors-creation-script.sql
- type: org.apache.brooklyn.entity.group.DynamicCluster
name: My Cluster
id: cluster
brooklyn.config:
initialSize: 2
dynamiccluster.memberspec:
'$brooklyn:entitySpec':
type: org.apache.brooklyn.entity.webapp.tomcat.TomcatServer …
```
=> Expand relationship support to memberspecs

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.template.html, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.less, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.template.html, ui-modules/blueprint-composer/app/components/providers/palette-service.provider.js, ui-modules/blueprint-composer/app/index.js, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.html, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.html, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.less, ui-modules/blueprint-composer/app/views/main/main.less, ui-modules/blueprint-composer/app/views/main/main.template.html, ui-modules/utils/br-core/style/buttons.less
#84 introduces the separable palette/config panel
this enhances that so that the palette gets the right size, and also fixes extension points and makes it so the "add (member spec)" usage of the panel respects those extension points
minor tidies to dropdowns and other style points also
=> new layout (separable palette) tidies

docs/customizations.md, ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.template.html, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector-palette-footer.html, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.less, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.template.html, ui-modules/blueprint-composer/app/components/providers/palette-service.provider.js, ui-modules/blueprint-composer/app/components/providers/recently-used-service.provider.js, ui-modules/blueprint-composer/app/index.js, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.html, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.html, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.less, ui-modules/blueprint-composer/app/views/main/main.less, ui-modules/blueprint-composer/app/views/main/main.template.html, ui-modules/blueprint-composer/package.json, ui-modules/utils/br-core/style/buttons.less
store how recently an entity or palette icon was used in the composer, and introduce a filter and sort to use this info.  also move sorts and dropdown to new places as shown below.  fix sort (was not working), allow multi-sort (just remembers the last things you sorted from, does not show them), and add a footer to describe the results of sorts and filters
builds on #93 so review that first (or review the two togethers
=> Composer recent and filters

ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.less, ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.template.html, ui-modules/blueprint-composer/app/components/designer/designer.directive.js, ui-modules/blueprint-composer/app/components/filters/entity.filter.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.html, ui-modules/blueprint-composer/app/views/main/graphical/edit/add/add.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.html, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.js
Several things to make composer easier to use:
* When searching in palette, it now sorts by "Relevance" as primary order; relevance formula is a bit complicated, poor-man's AI :), but works pretty damn well (!)
* Sort is always multi-sort, and dropdown shows the sort order (this could do with more UI goodness to make that obvious, but it does the right thing if you interact with it; "relevance" above obviously has no effect when not searching so "name" as second-order search order is what you normally get)
* Default palette now shows 3 wide; with more height and longer names this seems better (4 wide aka "Compact" is an option)
* the Quick Info pane from the palette is now toggleable, and showing this is the default action if you click on a tile (not adding to the root of the application …
=> Relevance and other composer tweaks

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js, ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.modal.template.html
previously showed "untitled" if you clilcked to expand on a new blueprint, now defaults to tidied version of display name (which is required)
=> improve logic and ui for inferring bundle and type name when saving to catalog

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js, ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.modal.template.html, ui-modules/blueprint-composer/app/views/main/main.controller.js
in line with https://github.com/apache/brooklyn-server/pull/1015
also when using a template the metadata is not populated as the intention is probably not to overwrite,
unless the user selects to save it as a template
=> catalog saver to support 'application', 'template', and 'entity'

ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.template.html, ui-modules/blueprint-composer/app/components/custom-config-widget/suggestion-dropdown.html, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/index.js, ui-modules/utils/script-tag-non-overwrite/script-tag-non-overwrite.js
by default `<script>` will install to template cache whenever it is processed as a directive.
this decorates it to be no-op if there is already something in the cache with that name,
allowing programmatic overrides of templates configured using `<script id="...">` notation.
=> Fix template overrides - decorate `script` directive to prevent re-overriding of templates

ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.js, ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js
Allows a blueprint to use `brooklyn.parameters`, and to reference that parameter using the DSL editor.
For example, I wrote the blueprint below in YAML (except the values of foo and bar), then switched to graphical view. I used the DSL editor to set the values for foo and bar to reference the brooklyn.parameters at the top-level app and on another entity.
```
brooklyn.config:
toplevelkey: toplevelval
brooklyn.parameters:
- name: toplevelParam
services:
- type: server
id: server1
brooklyn.parameters:
- name: MyParameter
type: string
- type: server
id: server2
brooklyn.config:
bar: '$brooklyn:component("server1").config("MyParameter")'
foo: '$brooklyn:parent().config("toplevelParam")'
```
=> DSL editor: support referencing `brooklyn.parameters`

modularity-server/features/pom.xml, ui-modules/app-inspector/pom.xml, ui-modules/app-inspector/src/main/webapp/WEB-INF/web.xml, ui-modules/blueprint-composer/pom.xml, ui-modules/blueprint-composer/src/main/webapp/WEB-INF/web.xml, ui-modules/blueprint-importer/pom.xml, ui-modules/blueprint-importer/src/main/webapp/WEB-INF/web.xml, ui-modules/catalog/pom.xml, ui-modules/catalog/src/main/webapp/WEB-INF/web.xml, ui-modules/features/pom.xml, ui-modules/groovy-console/pom.xml, ui-modules/groovy-console/src/main/webapp/WEB-INF/web.xml, ui-modules/home/pom.xml, ui-modules/home/src/main/webapp/WEB-INF/web.xml, ui-modules/location-manager/pom.xml, ui-modules/location-manager/src/main/webapp/WEB-INF/web.xml, ui-modules/logout/pom.xml, ui-modules/logout/src/main/webapp/WEB-INF/web.xml, ui-modules/rest-api-docs/pom.xml, ui-modules/rest-api-docs/src/main/webapp/WEB-INF/web.xml
the REST API has always been secured but we now secure these static assets also;
this gives a better experience on login, and it will be even more important when
we introduce oauth-based logins where the redirect page (served by the LoginModule
defined in the REST API module, connected to the LoginService defined in the jetty bundle,
both in brooklyn-server) should be served in response to the request for index.html,
not just on the REST calls
=> require login to webconsole for webapps

ui-modules/app-inspector/app/components/entity-policy/entity-policy.less, ui-modules/app-inspector/app/components/entity-policy/entity-policy.template.html
This was broken in Brooklyn previously: a white empty box was displayed instead of the form to edit the value.
This changes makes it cleaner and working as expected
=> Fix the inline edit configuration for the policies in app inspector

ui-modules/blueprint-composer/app/components/custom-config-widget/suggestion-dropdown.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
now if *.error is set, the widget silently falls back to the default.
if a user clicks to show the custom widget, the error message is shown.
subsequent custom widget toggles hide or show the error.
this lets people writing custom widgets handle errors gracefully
=> handle errors in custom widgets better

ui-modules/utils/table/index.js
without this if you put _two_ tables in the same parent controller view they collide on their data and have their own data
=> tables should run with their own scope

ui-modules/blueprint-composer/app/components/util/d3-blueprint.js
This is useful when working on a large screen. We can now zoom in 30% more
=> Allow bigger zoom in, for large screen mainly

ui-modules/location-manager/app/views/detail/detail.controller.js, ui-modules/location-manager/app/views/wizard/advanced/advanced.controller.js, ui-modules/location-manager/app/views/wizard/byon/byon.controller.js, ui-modules/location-manager/app/views/wizard/cloud/cloud.controller.js
The error message from the exception thrown when the user has been not entitled to one action is wrapped on an object and was not showed properlly in some places.
=> Solver error showing entitlements messages

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/components/util/d3-blueprint.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js, ui-modules/blueprint-composer/app/index.less, ui-modules/utils/br-core/style/buttons.less, ui-modules/utils/br-core/style/variables.less, ui-modules/utils/yaml-editor/addon/schemas/blueprint.json
* now supports map syntax in the visual editor (previously gave errors)
* now works without complaining if no services set
* leaves a marker in place if a location is removed (so consumers can avoid applying defaults or reset defaults)
* fixes bug where images broke during d3 transitions
* rationalises style files, moving similar things together and promoting some shareable things
=> Fix errors around locations in composer

ui-modules/app-inspector/app/components/providers/entity-api.provider.js, ui-modules/app-inspector/app/views/main/inspect/summary/summary.controller.js, ui-modules/catalog/app/views/bundle/bundle.state.js
Now shows the messages from the entitlement control system
=> Fix entitlement messages

ui-modules/rest-api-docs/app/views/main/main.controller.js
In internet isolated environments is impossible reaching the `swagger.json` file, and an error label is shown in the REST API Doc page.
Passing `null` as validator url, the module don't show the validation label as it does when is executed in localhost.
=> Avoiding swagger validation

ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.template.html, ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/components/util/d3-blueprint.js
has a field-based mode and JSON mode
builds on #118 , makes it mergeable
ideally flaws in the PR can be tracked here but addressed in follow-on PRs unless critical.  i'm aware of the following wishlist items:
1. if no params, it's not obvious how to add ("No params" should have option to "Add" one)
2. are the icons in top-right of params section needed (filter etc)
3. if same parameter entered twice you get angular errors
4. parameters section should appear only on application (it's pointless elsewhere)
5. parameters added should show up in the config section (maybe?)
6. do all the fields work as expected when defining a parameter used subsequently (eg label, constraint)
7. parameters are mostly pointless if you're deploying directly, it's mainly for saving and reuse (or some types of …
=> UI for defining parameters

ui-modules/app-inspector/app/index.js, ui-modules/blueprint-composer/app/index.js, ui-modules/catalog/app/index.js, ui-modules/home/app/index.js, ui-modules/location-manager/app/index.js, ui-modules/logout/app/index.js, ui-modules/shared/config/build/webpack.config.js
This does the following:
- enable debug logs for non-production builds
- enable angular runtime logs for non-production builds
- remove the `drop_console` option from webpack to display info, warn and error logs on production builds
=> Fix UI modules logs

ui-modules/home/app/views/main/deploy/deploy.controller.js, ui-modules/home/app/views/main/main.controller.js, ui-modules/utils/quick-launch/quick-launch.html, ui-modules/utils/quick-launch/quick-launch.js, ui-modules/utils/quick-launch/quick-launch.less
the effect is to open the template's definition in composer
viz, clicking one of the quick-launch templates show
`YAML` opens the in-modal editor (as before), but the new `Open in Composer` takes you to:
the location and config are as selected in quick launch, with the full original template
=> add an "Open in Composer" button to quick launch

ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js
When switching between pagination mode the number of displayed items was never reduced, because rowsPerPage was calculated based on the height of the scrolling view. Changed to be calculated based on the height of the non-scrolling container instead. List and compact list are now paginated where previously all items were displayed.
https://issues.apache.org/jira/browse/BROOKLYN-619
=> corrects pagination issue

ui-modules/utils/yaml-editor/addon/lint/lint-yaml-brooklyn.js
Previously in `blueprint-importer` you'd see errors in validation no matter what you did.  This is because the `catalogValidator` was incorrectly configured.  This fixes that.  It then tidies the code to reuse an instance (rather than reparse the schemas on every validation request!).
=> Fix importer linting

ui-modules/blueprint-composer/app/views/main/main.controller.js, ui-modules/blueprint-composer/app/views/main/yaml/yaml.state.js, ui-modules/utils/quick-launch/quick-launch.js
In a lot of edge cases, the "Open in Composer" button from quick launch generated errors.
This fixes many of the errors, and in cases where there are errors the composer responds sensibly (logging warning, and if yaml mode requested, preserving the input yaml).
=> Fix composer open

ui-modules/utils/catalog-uploader/catalog-uploader.html, ui-modules/utils/catalog-uploader/catalog-uploader.js
Corrects a bug where uploading a file to the catalog via the file picker did not work.
https://issues.apache.org/jira/browse/BROOKLYN-624
Resolves an issue with the getCatalogItemUrl method, which checks for the existence of a string 'org.apache.brooklyn.api.location.Location' in item.supertypes to determine the format of the url:
- Adds a check for the existence of the property supertypes before calling 'includes' on it.
- Checks for the string in item.tags if the supertypes property is not present.
=> add custom onChange directive to correct file uploader bug

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/utils/quick-launch/quick-launch.js
- if using quick launcher or catalog "deploy", it ignored the version; now it respects the version
- in composer, it could break if a config value was null, now it guards against that
- in composer, name wrapping was only permitted for words, which meant `type.name.xxxxxx` wouldn't wrap; now it can wrap anywhere
=> minor cleanups with version + NPE

pom.xml
Version 1.3 was causing NPE under some environments, especially when using the `make-release-artifacts.sh` script. The latest version fixes this issue + a couple of others.
=> Update frontend-maven-plugin version

ui-modules/app-inspector/app/components/entity-tree/entity-tree.directive.js, ui-modules/app-inspector/app/components/entity-tree/entity-tree.html, ui-modules/app-inspector/app/views/main/main.controller.js, ui-modules/app-inspector/app/views/main/main.less, ui-modules/app-inspector/app/views/main/main.template.html
https://issues.apache.org/jira/browse/BROOKLYN-620
Data retrieved from the application api does not contain any time information. 
To allow ordering by time we have to make a further call to entityApi.entityActivities. This returns an array of all activities. We take the startTimeUtc value of the first entry as the application start.
However...
The application data is updated frequently and this erases the time information. To avoid having to make multiple api calls (which causes an annoying flicker on the screen) we store the time information locally in an array of objects. For existing applications we can simply merge this time information with the refreshed data. For new applications, we temporarily set the startTimeUtc to the current time to ensure it's at the top of the list and then …
=> add time information to application data to allow ordering launch time

pom.xml
extends #160 offering a way for downstream projects to customize relative path if it causes issues
=> Relative path configurable

pom.xml
The issue was fixed in version 1.9.0 of the plugin, see: https://github.com/eirslett/frontend-maven-plugin/issues/820#issuecomment-570634363
=> Fixing an issue when building brooklyn-ui for downstream projects

ui-modules/home/app/views/main/deploy/deploy.controller.js, ui-modules/home/app/views/main/deploy/modal.template.html, ui-modules/home/app/views/main/main.controller.js, ui-modules/utils/quick-launch/quick-launch.html, ui-modules/utils/quick-launch/quick-launch.js
apply catalog_quick_launch tag to filtering locations,
if there is a single location select it automatically,
and if these tags are used, suppress the "create a new location" message --
thus making quick-launch suited for a neatly curated simple mode
where a single preferred location is tagged and you can simply click "deploy"
in quick launch without needing to set anything (assuming default config is valid in the blueprint)
=> auto-set a name for the app in quick-launch, and

pom.xml, ui-modules/home/package.json
This fixes an issue when trying to build on a clean machine or following the docker build instructions at https://github.com/apache/brooklyn/blob/master/README.md
=> Bumps npm, node, and webpack versions

pom.xml
brooklyn builds fine without this, but downstream projects get a warning when trying to reference this parent, unless we write the flattened pom to the mvn repo
=> use the flattened pom so that revision is set correctly

pom.xml
This reverts commit e8dec48eae0b07d1d2918c7315b1090e5c856345.
Seems maven doesn't actually respect a variable in relative path. I must have been taking some cached or downloaded item when i tested, as when we change the version it breaks.
Also irritating, seems maven won't look in the local reactor model so we need either relative path to work or the upstream item to have been built.
=> Revert "allow relative path to parent to be configured"

modularity-server/external-modules/pom.xml, modularity-server/metadata-registry/pom.xml, modularity-server/module-api/pom.xml, modularity-server/proxy/pom.xml
brooklyn dependencies use brooklyn.version normally except for a few
places.  Changed for consistency.
=> Use consistent version numbers

ui-modules/app-inspector/app/index.html, ui-modules/app-inspector/app/index.js, ui-modules/app-inspector/package.json, ui-modules/blueprint-composer/app/components/providers/tab-service.provider.js, ui-modules/blueprint-composer/app/index.html, ui-modules/blueprint-composer/app/index.js, ui-modules/blueprint-composer/app/views/main/main.controller.js, ui-modules/blueprint-composer/app/views/main/main.template.html, ui-modules/blueprint-composer/package.json, ui-modules/blueprint-importer/app/index.html, ui-modules/blueprint-importer/app/index.js, ui-modules/branding/brand-angular.js, ui-modules/catalog/app/index.html, ui-modules/catalog/app/index.js, ui-modules/groovy-console/app/index.html, ui-modules/groovy-console/app/index.js, ui-modules/home/app/index.html, ui-modules/home/app/index.js, ui-modules/location-manager/app/index.html, ui-modules/location-manager/app/index.js, ui-modules/logout/app/index.html, ui-modules/logout/app/index.js, ui-modules/rest-api-docs/app/index.html, ui-modules/rest-api-docs/app/index.js, ui-modules/shared/config/build/webpack.config.js
Each "tab" is added via a new `TabProvider` and can be removed/updated later on by the application config hook. Each tab is an object with the following properties:
- `title`: the tab title that is going to appears on the tab bar
- `stateKey`: the key of the state to switch to when the tab is clicked on
- `icon`: (optional) the class name for the font-awesome icon to use
=> Make the blueprint composer tabs customisable by downstream projects

ui-modules/catalog/app/views/bundle/bundle.state.js, ui-modules/catalog/app/views/bundle/bundle.template.html, ui-modules/utils/providers/catalog-api.provider.js
This adds a new `Download` button on the bundle page that let a user downloading the current bundle as a ZIP file.
This requires https://github.com/apache/brooklyn-server/pull/1131 to work
=> Add support for downloading bundle as ZIP files

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
On the spec editor, if an entity has a configuration key of type `integer`, with a `defaultValue` of `0`, then the `Configuration` section displayed `(empty)` because `defaultValue == ''` is true, whereas `defaultValue === ''` is false, which is what we want
=> Use `===` to not only check the value but type

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
with a little "eye" icon which toggles whether the value is masked (omitted) or shown.
uses same logic as the `sensitive-field` util widget, viz containing "secret" or "password" or "private" etc
clicking the slashed eye causes unmasking:
when collapsed in unmasked mode it appears like any other widget:
in unmasked mode, expanding and clicking the (unslashed) eye re-masks it:
=> fields detected as likely "sensitive" now masked in composer by default

ui-modules/utils/yaml-editor/yaml-editor.js
The YAML editor can now listen for an event with name `brooklyn.component.yaml-editor.cm` and will execute the given callback with the CodeMirror instance. That allows downstream project to use directly `CodeMirror` if they wish too.
=> Expose the CodeMirror instance that can be accessed via an event

ui-modules/blueprint-importer/app/index.html
Currently, it will throw an error when the module is started, making it unusable.
=> Use the correct AngularJs module name for blueprint importer

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js
When the spec editor first opens the filters are set to 'Suggested' 'Required' and 'In Use'.
This may result in no results being shown which is confusing to the user as it's not immediately obvious that there are filters in use.
In this situation we add the 'All' filter to show all results. Subsequent operation of the filters is unaffected.
=> Remove initial filter if no results

ui-modules/blueprint-composer/app/index.js, ui-modules/blueprint-composer/app/views/main/main.controller.js, ui-modules/blueprint-composer/app/views/main/yaml/yaml.state.js
the previous refactor left a reference to `isYamlMode` which it removed.  this reinstates that.
we will also want better redirection from the `/yaml?blueprint=xxxx` endpoint links from catalog for those cases where the blueprint is in a non-CAMP format, to allow the correct tab to display.  this adds some placeholder logic for that but does not implement it.
=> fix isYamlMode bug and placeholder for auto-detecting yaml state

ui-modules/location-manager/app/components/location-utils/location-utils.js
so that people can specify "16 gb" which is more natural than requiring eg "16384" (units hardcoded as "Mb")
=> remove units from minRam in location wizard

modularity-server/features/pom.xml
Noticed the duplicate plugin. Maven complained about it.
=> Removed duplicate instance of build-helper-maven-plugin plugin

ui-modules/blueprint-composer/app/components/designer/designer.less, ui-modules/blueprint-composer/app/components/util/d3-blueprint.js, ui-modules/blueprint-composer/app/views/main/main.controller.js, ui-modules/blueprint-composer/package.json
based on a `ui-composer-annotation` tag with text value or object value, rendering as markdown
see docs PR to follow immediately
teaser screenshot
from code
```
name: Annotation Sample
services:
- type: aws_s3_bucket
brooklyn.tags:
- ui-composer-annotation: A simple default annotation
- ui-composer-annotation:
text: >-
Shown below, yellow text, centered with CSS. Because it's long, scroll bars horizontally and vertically shown when
needed.
styleInnerDiv: 'margin: auto; color: yellow;'
'y': 120
- type: aws_s3_bucket
brooklyn.tags:
- ui-composer-annotation:
text: |
A **red** tag at _right_, using markdown, in a big box.
width: 300
height: 200
x: 220
'y': 0
background: '#ffcccc'
style: 'font-size: 9px;'
```
=> blueprint composer can show annotations

ui-modules/blueprint-composer/app/views/main/main.controller.js, ui-modules/catalog/app/views/bundle/type/type.state.js, ui-modules/catalog/app/views/bundle/type/type.template.html
Edit with YAML editor and Graphical editor now work for multiple yaml plan formats.
=> Added fix for catalog 'edit in' links

ui-modules/blueprint-composer/app/components/designer/designer.less, ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/util/d3-blueprint.js, ui-modules/blueprint-composer/app/views/main/main.controller.js
Switch relationships with path and label selector rather than whole relationship group, relationships can belong to sub-groups to be managed separately
=> Switch relationships with path and label selector rather than group selector

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/quick-fix/quick-fix.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.html, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.less
This will check if an entity has implicit inherited config keys. If this is the case, then warnings will be created for these config keys. Additionally, a quick fix will be available to automatically set the implicit inherited config key `x` to `$brooklyn:parent().config("x")`
Here it is in action:
=> Add support for an ancestor quick fix

ui-modules/app-inspector/app/components/task-list/task-list.directive.js
By default, AngularJS does not reevalute an expression if the left part doesn't change. This is exactly what happens with the `timeAgoFilter`: the timestamp never changes obviously and therefore, the display keeps displaying the evaluated value at the moment of the first page display.
Marking the filter as `stateful` forces AngularJS to reevaluate when the scope changes.
By doing this, the task list (App Inspector) now updates the started time column on the fly
=> Make the timeAgoFilter stateful so it keeps updating the display

ui-modules/blueprint-composer/app/components/designer/designer.less
This addresses an issue on Windows browsers where the confirmation frame of the composer has scrollbars when it shouldn't.
=> fix for scrollbars appearing in composer confirmation frame

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
Default values were not being checked properly from Parameters and Configuration fields erroneously had *required* label
=> Fixed Composer required label check

ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js
Added a default displayName=symbolicName to prevent unwanted clustering
Avoids fallback to 'lastUsed' attribute with which elements are moved around as they are used
=> Entity sorting correction

modularity-server/external-modules/pom.xml, modularity-server/external-modules/src/main/java/org/apache/brooklyn/ui/modularity/ExternalUiModule.java, modularity-server/metadata-registry/pom.xml, modularity-server/metadata-registry/src/main/java/org/apache/brooklyn/ui/modularity/metadata/registry/impl/UiMetadataConfigListener.java, modularity-server/metadata-registry/src/main/java/org/apache/brooklyn/ui/modularity/metadata/registry/impl/UiMetadataRegistryImpl.java, modularity-server/module-api/src/main/java/org/apache/brooklyn/ui/modularity/module/api/UiModuleListener.java, modularity-server/module-registry/src/main/java/org/apache/brooklyn/ui/modularity/module/registry/UiModuleRegistryImpl.java
(1) metadata service appeared to have an inconsistent naming strategy; when i updated the PID/name as done here it worked perfectly, matching the location metadata cfg files we install.
(2) this also seems to for now get rid of these errors in the startup log
```
2021-09-01T09:07:05,357 - ERROR 374 o.a.b.u.m.ExternalUiModule [FelixStartLevel] bundle org.apache.brooklyn.ui.modularity.brooklyn-ui-external-modules:1.1.0.SNAPSHOT (374)[org.apache.brooklyn.ui.modularity.ExternalUiModule] : Cannot register component
2021-09-01T09:07:05,372 - ERROR 375 o.a.b.u.m.m.r.i.UiMetadataConfigListener [FelixStartLevel] bundle org.apache.brooklyn.ui.modularity.brooklyn-ui-metadata-registry:1.1.0.SNAPSHOT (375)[org.apache.brooklyn.ui.modularity.metadata.registry.impl.UiMetadataConfigListener] : Cannot …
```
=> attempt to fix WARN and ERROR on service creation, and tidy some references and logs

ui-modules/home/app/index.html, ui-modules/home/app/index.js, ui-modules/home/app/index.less, ui-modules/home/app/views/about/about.controller.js, ui-modules/home/app/views/about/about.template.html, ui-modules/utils/api/brooklyn/server.js, ui-modules/utils/persistence-importer/persistence-importer.html, ui-modules/utils/persistence-importer/persistence-importer.js, ui-modules/utils/persistence-importer/persistence-importer.less
Introducing a directive to allow uploading (importing) of a persistence store archive (currently zip only).
Introducing capability to download (export) the current persistent store.
=> Persistence import directive / export download implementation

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
... actually a `config[key]` was undefinded and breaking the composer. This happens when config values are maps containign DSL values, such as the 3tier app where tomcat is configured to connect to the database using a CAMP DSL expression. 
Bug introduced when adapting Brooklyn UI to accept redering of relationships.
=> Added fix for this

ui-modules/catalog/app/views/bundle/type/type.state.js, ui-modules/utils/quick-launch/quick-launch.js
For support of both camp and tosca types at the same time:
Previously:
camp type had a post processor applied to it, that translated it to tosca
API to process the deployment on the server side received the tosca 1.3 template with format as tosca13
server translate the template back to camp and deploys the application
Above is unnecessary conversion back and forward and also has some side effects (such as an unnecessary delete effector).
With the change:
if using camp type, we don't apply post processors
API sends a camp template to the server
=> ensuring that tosca post processors are not applied if type is camp

ui-modules/catalog/app/index.js, ui-modules/catalog/app/index.less, ui-modules/catalog/app/views/bundle/bundle.state.js, ui-modules/catalog/app/views/bundle/bundle.template.html, ui-modules/location-manager/app/index.js, ui-modules/location-manager/app/views/detail/detail.controller.js, ui-modules/location-manager/app/views/detail/detail.template.html, ui-modules/utils/catalog-deleter/catalog-deleter.html, ui-modules/utils/catalog-deleter/catalog-deleter.js, ui-modules/utils/catalog-deleter/catalog-deleter.less
This adds popups on catalog-item deletion (bundle and locations; no delete for type, though some support is in here for that) which:
* advise if you are are deleting a non-deleteable bundle, that the deletion is temporary
* if you are deleting a type from a bundle (only a location supported through UI at present), it advises whether the bundle will also be deleted, and if not it gives you the option to review it and delete it instead
* advises that if you have deployments using the type bad things can happen
For example:
location in dedicated single-location bundle
and location in larger bundle:
and user bundle:
and system bundle:
=> use new deleteable flag on bundles to give better info on delete

modularity-server/module-api/src/main/java/org/apache/brooklyn/ui/modularity/module/api/UiModule.java, modularity-server/module-api/src/main/java/org/apache/brooklyn/ui/modularity/module/api/internal/UiModuleImpl.java, ui-modules/app-inspector/package.json, ui-modules/app-inspector/src/main/resources/ui-module/config.yaml, ui-modules/home/app/index.js, ui-modules/home/app/views/main/main.controller.js, ui-modules/login/package-lock.json, ui-modules/utils/module-links/module-links.js, ui-modules/utils/utils/general.js
Allows to set up an order for listing the modules in the home page and the header menu. Also it renames the `App inspector` to just `Inspector` as it Apache Brooklyn can manage more than applications.
=> Add `order` as module property and use it when is present before using name for ordering modules

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
When an entity don't have a name, it shows the entity `ID` only when is provided instead the `typeName`
If no ID is provided it still shows the `typeName` instead the interal generated id as is shown in the `id` field
https://user-images.githubusercontent.com/17095501/173815479-0b4f422a-7b9e-482d-a3ce-0e96b5d059b3.mov
=> When an entity don't have a name, it shows the personalised entity `ID`

ui-modules/blueprint-composer/app/components/designer/designer.directive.js, ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.less, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/components/util/model/dsl.model.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.spec.js, ui-modules/utils/autogrow/index.js
Previously we used regex on key names to determine if the contents was an entity spec.  This meant some (eg multi-group) didn't work and in some cases could make the UI unusable or broken.
This checks the actual type defined for the key name and of the value if the type is Object and so supports entity spec
either if:
- it uses the DSL word
- the key type matches
- the key name matches (fallback for where type is unknown/not-loaded and value not set)
and in multiple places:
- in model
- in designer view canvas
- in spec editor
Also makes minor related improvements to UI and code.
=> Improve handling of spec types in composer

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js, ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html, ui-modules/blueprint-composer/app/components/util/model/entity.model.js
versions set either in the yaml or by a user in the dropdown are fixed.
otherwise no version is stored.
fixes bad behaviour where previously, switching to composer would hard-code versions everywhere, _changing_ the blueprint (introduced in #292)
=> don't hard-code a version in composer unless explicitly set

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js, ui-modules/blueprint-composer/app/components/quick-fix/quick-fix.js, ui-modules/blueprint-composer/app/components/util/model/entity.model.js, ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.less
- reference to ancestor without ID caused null, now it sets the id
- reference to ancestor fix always just pointed at parent, not where config was defined
- count of errors was sometimes not reset so was too high
- alignment of error line marker was wrong
=> fix issues around quick fixes

ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.js
fix for using the entity id properly to include all entities properties (previously wrongly removed as non-unique):
* The problem happens when there are multiple entities of the same type. When filtering by entities, we can see that only the one that was added first has all items, the others only have a single item - the entity itself
* there is a function in dsl-editor.js - uniqueItemsthat filters items based on the name of prop and entity id.  This function gets called by three distinct categories: config, sensors and entities (functions getConfigItems,getSensorItems and getEntityItems  respectively)
* When calling in from the entity, the property entity.id is present, hence we get the entity itself in the list
* However, when called via sensors/config, the entity.id is undefined (the …
=> fix non-unique properties not being included

ui-modules/utils/quick-launch/quick-launch.html
Corrected syntax on the `ng-switch` directive so that config fields with non-String type are rendered as intended.
=> field type syntax fix

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js
Refactoring to avoid regression from previous changes that caused the "version" URL components of this link to be `undefined`.
=> fix for missing version in 'View in Catalog' link

ui-modules/app-inspector/app/views/main/inspect/management/management.less
Tidies the new policy layout screen to remove the excess padding and align the buttons correctly
Before:
After:
=> Tidies layout of new-policy screen

ui-modules/utils/quick-launch/quick-launch.js
Added check that parsedPlan.services exists before checking its length, which would be causing an issue for extensions that fo not have a `parsedPlan.services`
=> Added check that parsedPlan.services exists before checking its length

ui-modules/app-inspector/app/components/workflow/workflow-steps.less
This should fix issues with displaying long IDs for workflow steps without them escaping the panel:
=> wrapping long step id text

Dockerfile
The previous version (maven:3.5.4-jdk-8) was failing with 404 errors when performing `apt-get update`. This bumps the base image to the latest version (maven:3.8.6-jdk-8)
=> Bumps version of maven Docker image used for CI
