src/test/javascript/specs/model/application-spec.js
src/test/javascript/specs/model/entity-summary-spec.js
src/test/javascript/specs/model/location-spec.js

Depends on https://github.com/apache/brooklyn-server/pull/15

Remove /v1 prefix from REST API

---

pom.xml
src/test/javascript/specs/model/application-spec.js
src/test/javascript/specs/view/application-explorer-spec.js

Due to 2.X requiring maven 3.1.0

Rollback version of jasmin-maven-plugin to 1.3.1.6

---

src/main/license/source-inclusions.yaml
src/main/webapp/assets/css/base.css
src/main/webapp/assets/css/easy-autocomplete.css
src/main/webapp/assets/css/styles.css
src/main/webapp/assets/js/config.js
src/main/webapp/assets/js/libs/jquery.easy-autocomplete.js
src/main/webapp/assets/js/router.js
src/main/webapp/assets/js/view/catalog.js
src/main/webapp/assets/js/view/editor.js
src/main/webapp/assets/js/view/home.js
src/main/webapp/assets/js/view/location-wizard.js
src/main/webapp/assets/tpl/editor/location-alert.html
src/main/webapp/assets/tpl/home/summaries.html
src/main/webapp/assets/tpl/location-wizard/location-configuration.html
src/main/webapp/assets/tpl/location-wizard/location-provisioning-entry.html
src/main/webapp/assets/tpl/location-wizard/location-provisioning.html
src/main/webapp/assets/tpl/location-wizard/location-type.html
src/main/webapp/assets/tpl/location-wizard/modal.html
src/test/javascript/config.txt

Add a location wizard:
This will be display on:
1. the home page if there is no locations defined. The location number becomes a button to add a location. The wizard will be displayed as a modal in this case
2. the catalog page, when clicking on the add location button
3. the YAML editor page if there is no locations defined. The wizard will be displayed as a modal in this case

Location wizard

---

src/main/webapp/assets/css/codemirror-brooklyn.css

Follow up of my comment on #21

Update style of editor's error message

---

.gitignore
src/main/webapp/WEB-INF/web.xml
src/main/webapp/assets/css/base.css
src/main/webapp/assets/js/util/brooklyn-utils.js
src/main/webapp/index.html

Follow up to https://github.com/apache/brooklyn-server/pull/41

Request container authentication

---

src/main/webapp/assets/js/view/effector-invoke.js
src/main/webapp/assets/tpl/apps/param.html

This PR depends on https://github.com/apache/brooklyn-server/pull/185

Use password input for sensitive information

---

src/main/webapp/assets/css/codemirror-brooklyn.css

based on https://codemirror.net/demo/visibletabs.html

show tabs in CM editor

---

src/main/webapp/assets/html/swagger-ui.html
src/main/webapp/assets/js/view/entity-config.js
src/main/webapp/assets/js/view/entity-sensors.js
src/main/webapp/assets/js/view/viewutils.js
src/main/webapp/assets/tpl/app-add-wizard/create.html
src/main/webapp/assets/tpl/help/page.html
src/main/webapp/assets/tpl/home/applications.html
src/main/webapp/assets/tpl/home/server-caution.html
src/main/webapp/assets/tpl/labs/page.html
src/main/webapp/assets/tpl/script/groovy.html
src/main/webapp/assets/tpl/script/swagger.html
src/main/webapp/index.html

Allows you to move the brooklyn-ui from root 
Allows ui to be deployed behind a load balancer or `Web-ContextPath` changed via karaf

Make absolute paths relative

---

src/main/webapp/assets/js/util/brooklyn-utils.js
src/main/webapp/logout_redirect.html

- fix logout for Internet Explorer
- use get call to logout

BROOKLYN-323: Improve logout script

---

pom.xml

Switch to Java 8.
This depends on https://github.com/apache/brooklyn-server/pull/684.

Switch to Java 8

---

pom.xml

Related to https://github.com/apache/brooklyn-dist/pull/97 and https://github.com/apache/brooklyn-server/pull/741

Update maven-compiler-plugin to 3.6.1

---

src/main/webapp/assets/js/view/application-add-wizard.js

The endpoint used was changed to require a version. Assume latest.

Fix app wizard configuration load

---

src/main/webapp/assets/js/router.js

introduced by #754 returning correct json when advertising json

fix username in quotes

---

modularity-server/external-modules/pom.xml
modularity-server/metadata-registry/pom.xml
modularity-server/module-api/pom.xml
modularity-server/module-registry/pom.xml
modularity-server/proxy/pom.xml
pom.xml

Otherwise it pulls in old version of jackson

Version bumps to align with brooklyn server

---

pom.xml

thanks to @grkvlt for this fix

apply POM change to fix issue with npm install on windows

---

modularity-server/features/pom.xml
pom.xml
ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js
ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js
ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.less
ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.template.html
ui-modules/blueprint-composer/app/index.js
ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.js
ui-modules/blueprint-composer/app/views/main/main.controller.js

Minor changes to new UI, esp to composer, to allow it to be more easily extended and customized by downstream projects

Composer customizable

---

pom.xml

Sets the goals explicitly in profile configuration, to match plugin configurations.

Fix configuration for npm plugin on Windows

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
ui-modules/blueprint-composer/app/views/main/main.less
ui-modules/blueprint-composer/app/views/main/main.template.html

* give the right editor for generics in types
* open config section by default
* fix height of dropdown caret in top right

composer tidies

---

modularity-server/features/pom.xml

See https://github.com/apache/brooklyn-server/pull/995

Bump karaf to 4.1.6 (from 4.1.2)

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html

put a few more things on controller for use in custom widgets

Composer use controller

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js

Hook to allow downstream to modify the spec editor header

spec editor hook

---

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js

Does not include any specific changes for the configuration here, these can be added in future pull requests

Add callback for customising catalog save configuration

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js

if you are editting json in the spec editor, every valid change does a model update and changes the `$viewValue` to the stringified output `{"key":"vallue"}` which is unhelpful when you're trying to get useful spaces
this prevents the update if the `$viewValue` gives the same value, and if making a new value it nicely formats it

fix json editor state issues

---

ui-modules/utils/server-status/server-status.template.html

NO-CONNECTION message changed for the case something goes wrong with the session after some time of inactivity

Change NO-CONNECTION error message

---

ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.js
ui-modules/blueprint-composer/app/components/dsl-viewer/dsl-viewer.js
ui-modules/blueprint-composer/app/components/dsl-viewer/dsl-viewer.less
ui-modules/blueprint-composer/app/components/dsl-viewer/dsl-viewer.template.html
ui-modules/blueprint-composer/app/index.less

note that *DSL Editor* still doesn't support literal

DSL Viewer ignored literals; this fixes that and tidies the code a bit

---

ui-modules/utils/server-status/server-status.js
ui-modules/utils/server-status/server-status.template.html

Manages the errors that the back end send using the code on this PR: 
https://github.com/apache/brooklyn-server/pull/1079

Manage backend errors including expired sessions

---

features/pom.xml
modularity-server/features/pom.xml

This ensures that the GPG signatures for the feature files are
uploaded to the Nexus repository when creating a release

Changes packing from feature to pom

---

ui-modules/utils/quick-launch/quick-launch.js

Added condition for only undefined fields to be shown empty

Added condition for only undefined fields to be shown empty

---

ui-modules/catalog/app/views/catalog/catalog.state.js

Persists whether entities are sorted by bundle or type and the selected sort order.

persist sort-by information

---

ui-modules/utils/quick-launch/quick-launch.js

In the situation where I have config in my application template
and I deploy it from the catalog the config will now be used to fill
in the parameters.

Check for config in parsed Plan

---

ui-modules/app-inspector/app/components/providers/activity-api.provider.js

Stream type may be of form "Main artifact:
classpath://scripts/echos/configure.ps1" which is resovled by cxf as a
path

Encode Stream Type

---

ui-modules/app-inspector/app/components/entity-tree/entity-node.less

To better convey grouping within an application. Spacing between top-level application entities is maintained.

Web UI: tweak entity tree spacing

---

ui-modules/location-manager/app/components/location-utils/location-utils.js
ui-modules/rest-api-docs/app/views/main/main.controller.js

Two minor tweaks:
* location wizard text and add `windows` as an option
* rest api in alpha order

Alex tweaks

---

ui-modules/app-inspector/app/components/task-sunburst/task-sunburst.directive.js
ui-modules/app-inspector/app/components/task-sunburst/task-sunburst.less
ui-modules/app-inspector/app/components/task-sunburst/task-sunburst.util.js

Fix error re `hash` function not found.  Add ellipsis.  Start of horizontal label layout (but commented out).

Kilt tweaks

---

ui-modules/app-inspector/app/components/stream/stream.directive.js
ui-modules/app-inspector/app/components/stream/stream.less
ui-modules/app-inspector/app/components/stream/stream.template.html
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.controller.js

SMART-141 Add formatting for WinRM log stream

---

ui-modules/app-inspector/app/components/entity-tree/entity-tree.html
ui-modules/app-inspector/app/views/main/main.controller.js
ui-modules/app-inspector/app/views/main/main.template.html
ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector-palette-footer.html
ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.directive.js
ui-modules/blueprint-composer/app/components/catalog-selector/catalog-selector.less
ui-modules/blueprint-composer/app/views/main/graphical/graphical.state.less
ui-modules/blueprint-importer/app/views/main/main.controller.js
ui-modules/branding/brand.js
ui-modules/catalog/app/components/type-item/index.html
ui-modules/catalog/app/views/bundle/bundle.state.js
ui-modules/catalog/app/views/bundle/bundle.template.html
ui-modules/catalog/app/views/bundle/type/type.state.js
ui-modules/catalog/app/views/bundle/type/type.template.html
ui-modules/catalog/app/views/catalog/catalog.state.js
ui-modules/catalog/app/views/catalog/catalog.template.html
ui-modules/utils/icon-generator/icon-generator.js
ui-modules/utils/quick-launch/quick-launch.js

Allow to handle thousands of entities gracefully, and for the composer link to be customized.

UI efficiency and customisability

---

ui-modules/app-inspector/app/components/entity-tree/entity-tree.directive.js
ui-modules/app-inspector/app/components/providers/entity-api.provider.js
ui-modules/app-inspector/app/views/main/inspect/summary/summary.controller.js
ui-modules/app-inspector/app/views/main/inspect/summary/summary.template.html

Yup the blueprint section now contains a  list with the plan hierarchy.

Spec hierarchy tag

---

ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.js
ui-modules/blueprint-composer/app/components/util/model/dsl.model.js
ui-modules/blueprint-composer/app/components/util/model/dsl.model.spec.js
ui-modules/blueprint-composer/app/views/main/graphical/edit/dsl/edit.dsl.controller.js

Allow downstream to configure edit.dsl controller

---

ui-modules/utils/quick-launch/quick-launch.html
ui-modules/utils/quick-launch/quick-launch.js

Fix typos in isRequired condition

---

ui-modules/app-inspector/app/components/entity-tree/entity-tree.directive.js
ui-modules/app-inspector/app/views/main/main.controller.js

Improvements for relationship view processing in app inspector

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
ui-modules/blueprint-composer/app/components/util/model/issue.model.js

Add ID field to Issues model to distinguish issues for multiple properties with the same name

Improvements in validation of node properties (displaying Issues)

---

ui-modules/blueprint-composer/app/components/util/d3-blueprint.js

Inherit overflow style for confirmation menu

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.spec.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html

remove placeholder for "requirements" section wanted by downstream apps

make spec-editor sections re-orderable

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js

Entity relationhips provider API in blueprint service

---

ui-modules/blueprint-composer/app/views/main/main.controller.js
ui-modules/catalog/app/components/providers/quick-launch-overrides.provider.js
ui-modules/catalog/app/views/bundle/type/type.state.js
ui-modules/utils/quick-launch/quick-launch.js

Provide external version for YAML generator.

WIP: Fix/smart 121 part 3

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
ui-modules/blueprint-composer/app/components/util/d3-blueprint.js

Draw relationship path labels with textPath, if supplied

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
ui-modules/blueprint-composer/app/components/util/d3-blueprint.js
ui-modules/blueprint-composer/app/views/main/main.controller.js
ui-modules/blueprint-composer/app/views/main/main.less

Make relationship path and label selector configurable

---

ui-modules/blueprint-composer/app/components/designer/designer.directive.js

Improve performance of the blueprint processing on first load; introduce d3.metadata-refreshed event

---

ui-modules/blueprint-composer/app/components/designer/designer.directive.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js

Introduce d3.renamed and d3.removed events for the downstream to react on entity changes

---

ui-modules/utils/logbook/logbook.js
ui-modules/utils/logbook/logbook.less
ui-modules/utils/logbook/logbook.template.html

Re-position logbook query parameters, query result and query result filters for a better UX

---

ui-modules/utils/logbook/logbook.js
ui-modules/utils/logbook/logbook.less
ui-modules/utils/logbook/logbook.template.html

Add option to auto-refresh logbook widget with latest update

---

ui-modules/app-inspector/app/index.js
ui-modules/app-inspector/app/index.less
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.template.html
ui-modules/app-inspector/app/views/main/inspect/summary/summary.template.html
ui-modules/utils/logbook/logbook.js
ui-modules/utils/logbook/logbook.template.html

Logbook widget has been enhanced with multi-phrase search. `searchId` is now a minimum phrase to match with, if supplied in the directive arguments.

Logbook widget in app inspector

---

ui-modules/blueprint-composer/app/components/designer/designer.directive.js
ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
ui-modules/blueprint-composer/app/components/util/d3-blueprint.js
ui-modules/blueprint-composer/app/views/main/main.controller.js

Support multiple labels on the same relationship path

---

ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.template.html

Display icon in DSL editor search result only if there is one

---

ui-modules/blueprint-composer/app/components/designer/designer.directive.js
ui-modules/blueprint-composer/app/components/designer/designer.less
ui-modules/blueprint-composer/app/components/dsl-editor/dsl-editor.js
ui-modules/blueprint-composer/app/components/util/d3-blueprint.js

Filter Scope in DSL editor by clicking on the node on the canvas

---

ui-modules/blueprint-composer/app/components/util/d3-blueprint.js

Remove redundant logging in the blueprint graph

---

ui-modules/home/app/views/about/node-management/node-management.template.html

Fix for logic in enabling the apply button.
Previously button disabled when only state change. Now button enabled if either property is changed.

fix for incorrect logic for disabling apply button

---

ui-modules/utils/br-core/button/button.html
ui-modules/utils/br-core/button/button.js

Always download referenced resources if configured so

---

ui-modules/app-inspector/app/views/main/inspect/summary/summary.template.html

Displaying more location info in the location summary in app inspector.

Added proper display of locations to avoid confusions

---

ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.template.html
ui-modules/app-inspector/app/views/main/inspect/summary/summary.template.html
ui-modules/utils/logbook/logbook.js

UI changes for supportint  https://github.com/apache/brooklyn-server/pull/1241

Support entityId and taskId as parameters

---

ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.template.html

Offer to download streams output as txt file

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js

Add fix for disappearing link

---

modularity-server/metadata-registry/pom.xml

Added forgotten supported bundle type

---

modularity-server/metadata-registry/pom.xml

Added bundle type too

---

ui-modules/home/app/views/about/about.controller.js
ui-modules/home/app/views/about/about.template.html

Display error modal on HA operation failure

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html

Signed-off-by: Mykola Mandra <mykola.mandra@cloudsoft.io
https://user-images.githubusercontent.com/81319331/153579322-843fd0bd-c2fb-4b6c-9579-15c652512b45.mov
>

Do not display versions dropdown if there are no versions to show

---

ui-modules/blueprint-composer/app/components/util/d3-blueprint.js

https://user-images.githubusercontent.com/81319331/153613265-fe675259-ce46-424b-a3b4-a92ce71f4e2b.mov

Adjust arc coordinates after the rotation of member-spec item

---

ui-modules/app-inspector/app/components/entity-tree/entity-node.less

due to https://bugs.chromium.org/p/chromium/issues/detail?id=265303

remove transition style rule which breaks color inherit on chrome

---

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js
ui-modules/login/package-lock.json

Fix button name to update blueprint

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js

requires https://github.com/apache/brooklyn-server/pull/1311

support custom URLs in composer

---

ui-modules/app-inspector/app/components/entity-effector/entity-effector.directive.js
ui-modules/app-inspector/app/views/main/inspect/effectors/effectors.controller.js
ui-modules/app-inspector/app/views/main/inspect/effectors/effectors.template.html

Allow linking to an effector using `#!/application/ptbqxzuakn/entity/ptbqxzuakn/effectors?effector=restart`

Link to effector

---

ui-modules/app-inspector/app/views/main/main.less

Adjust width of switch view dropdown automatically

---

ui-modules/utils/logbook/logbook.js
ui-modules/utils/logbook/logbook.template.html

WIP
Requires [brooklyn-server#1316](https://github.com/apache/brooklyn-server/pull/1316)
Signed-off-by: Andrew Donald Kennedy <andrew.international@gmail.com>

Adds recursive LogBook query feature

---

ui-modules/blueprint-importer/app/index.js
ui-modules/groovy-console/app/index.js
ui-modules/location-manager/app/index.js
ui-modules/rest-api-docs/app/index.js
ui-modules/utils/utils/general.js

Fix an UI error introduced by no injecting the `brUtilsGeneral` in all the modules in #325

Fix issue generated in 325

---

ui-modules/app-inspector/app/components/stream/stream.directive.js
ui-modules/app-inspector/app/components/stream/stream.template.html

Display raw CLI XML content first if WinRM stream content is too big

---

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js
ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.modal.template.html
ui-modules/blueprint-composer/app/components/providers/palette-api.js
ui-modules/blueprint-composer/app/components/providers/palette-api.provider.js

Improve adding new versions of a type to existing bundles

---

ui-modules/utils/quick-launch/quick-launch.js

Improve handling of config value

---

ui-modules/app-inspector/app/components/entity-tree/entity-tree.directive.js

Cover visibility edge-case for moved entities in a praticular view

---

ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.directive.js
ui-modules/blueprint-composer/app/components/spec-editor/spec-editor.template.html
ui-modules/blueprint-composer/app/components/util/model/entity.model.js

Fix parameter editing UX issue

---

ui-modules/app-inspector/app/components/stream/stream.directive.js
ui-modules/app-inspector/app/components/stream/stream.template.html

Check if to drop stream filters for stream with CLI XML content only

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js
ui-modules/utils/quick-launch/quick-launch.html

Do not ignore location version in the UI

---

ui-modules/app-inspector/app/components/loading-state/loading-state.directive.js
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.controller.js
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.template.html

to pass html into loading-error

show logbook widget for 404 tasks, and new trust-error option

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js

Fix parameter validation with the regex constraint

---

ui-modules/blueprint-composer/app/components/util/model/entity.model.js

Fix overwrite rule when adding a config key definition

---

ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.directive.js
ui-modules/blueprint-composer/app/components/catalog-saver/catalog-saver.modal.template.html

Catalog-saver improvements

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js

Test constraint regex value in composer as a full line match

---

ui-modules/app-inspector/app/components/config-sensor-table/config-sensor-table.style.less
ui-modules/app-inspector/app/components/providers/activity-api.provider.js
ui-modules/app-inspector/app/components/providers/entity-api.provider.js
ui-modules/app-inspector/app/components/workflow/workflow-steps.directive.js
ui-modules/app-inspector/app/index.js
ui-modules/app-inspector/app/views/main/inspect/activities/activities.controller.js
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.controller.js
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.less
ui-modules/app-inspector/app/views/main/inspect/activities/detail/detail.template.html
ui-modules/app-inspector/app/views/main/inspect/inspect.controller.js
ui-modules/app-inspector/app/views/main/inspect/run-workflow-modal.template.html
ui-modules/utils/user-management/user-management.js
ui-modules/utils/yaml-editor/yaml-editor.js

Add panel to edit and re-submit a workflow from the UI
Fix some bugs and API updates in the workflow UI, including suppressing secrets for workflow and tasks
Depends on https://github.com/apache/brooklyn-server/pull/1369

Workflow UI improvements

---

ui-modules/blueprint-composer/app/components/providers/blueprint-service.provider.js

error not showing when using dsl for a parameter with a regex constraint

---

ui-modules/utils/api/brooklyn/server.js

add a leading slash to use absolute path in ha/persist/import
